name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1253a5daf30e5e72e9e8a561c3205ba114904014d15353e5b1ed424a3695a114"

[versions]
fabric = "0.15.3"
minecraft = "1.19.4"
