name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a290a1599ac10b0841be687fb87e8152f3555bbf9df428b3e876d3861c634911"

[versions]
fabric = "0.15.3"
minecraft = "1.19.2"
