name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "044297c371b30ae49edf7f67c1a41cddad2e0559de5055fc9110a0dff78531f3"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
