name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.19.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "818ab4adadeddec552692a0c0bccdd9f3458cf07105467f88b13b2907be7fe19"

[versions]
minecraft = "1.19.4"
quilt = "0.22.0"
