name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3cd02595909c58a9077967ae9a91dedcb47c6a49a26c6c3846752ab63f797fa"

[versions]
minecraft = "1.19.2"
quilt = "0.22.0"
