name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1301d6da2c1774a6897272311965ffdd4d18d20ee12b971ab8e300005ea4ac67"

[versions]
fabric = "0.15.3"
minecraft = "1.16.5"
