name = "Additive"
author = "SkywardMC"
version = "1.23.0+1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df487c04bd6f41b669f90d66c13b1da65c5466dfc64f379d3f9247ef1576e164"

[versions]
fabric = "0.15.3"
minecraft = "1.18.2"
